### Tasa de Desempleo
```{r, include=FALSE}
d <- serie_tasa_desempleo()

ult <- d %>% 
  tail(1) %>% 
  select(tasa_desempleo) %>% 
  pull() %>% 
  { ./100} %>% 
  percentc()

ultimo <- d %>% 
  tail(1) %>% 
  select(tasa_desempleo) %>% 
  pull()

inicio <- d %>% 
  filter(fecha %in% c(ymd(20200101))) %>% 
  select(tasa_desempleo) %>% 
  pull()

var <- ultimo - inicio 

var <- var %>% 
  { ./100} %>% 
  percentc()

peak <- d %>% 
  filter(tasa_desempleo == max(tasa_desempleo)) %>% 
  distinct(tasa_desempleo) %>% 
  pull() %>% 
  { ./100} %>% 
  percentc()
```

La tasa de desempleo actual es de un `r ult`. Desde inicios de año se observa un incremento del `r var`.

A partir de octubre 2019 notamos fuertemente un alza de este indicador efecto de dos hítos importantes: _Estallido Social_ y _Corona Virus_, incremento que no se observaba desde hace una década, **Crisis Subprime**, donde nuestro país alzanzo el peak mas alto de desempleo correspondiente a un `r peak`

**Definicion**: La _tasa de desempleo_ mide el nivel de desocupación en relación con la población activa.
En otras palabras, es la parte de la población que estando en edad, condiciones y disposición de trabajar (población activa), no tiene puesto de trabajo.
La tasa de desempleo es muy útil para conocer las personas que no están trabajando. Su fórmula de cálculo es la población de 16 años y más que no está trabajando y busca trabajo, dividido entre la población económicamente activa de 16 años y más, esto es, ocupados más desocupados.
