### Fallecidos por  Región

```{r, include = FALSE}
d <- serie_consolidado_region()

total_chile <- d %>% 
  filter(Fecha == max(Fecha)) %>% 
  select(fallecidos) %>% 
  pull() %>% 
  sum()

max_fallecidos <- d %>% 
  filter(Fecha == max(Fecha)) %>% 
  arrange(desc(fallecidos)) 

sum_top3_fallecidos <- max_fallecidos %>% 
  head(3) %>% 
  select(fallecidos) %>% 
  pull() %>% 
  sum()

sum_tail3_fallecidos <- max_fallecidos %>% 
  tail(3) %>% 
  select(fallecidos) %>% 
  pull() %>% 
  sum()

crecimiento_rm <- d %>% 
  filter(Fecha %in% c(max(d$Fecha), max(d$Fecha)-7), Region == "Metropolitana") %>% 
  select(Region, Fecha, fallecidos) %>% 
  mutate(Fecha = ifelse(Fecha == max(d$Fecha), "w", "w-1")) %>% 
  spread(Fecha, fallecidos) %>% 
  mutate(var = (w - `w-1`)/(`w-1`)) 

text_crecimiento_rm <- ifelse(crecimiento_rm$var > 0, "crecimiento", "decrecimiento")

```

Chile registra un total de `r commac(total_chile)` fallecidos al `r datec(max_fallecidos$Fecha[1])`. Las tres regiones con más casos acumulados de fallecidos son:

- `r max_fallecidos$Region[1]`: `r commac(max_fallecidos$fallecidos[1])`
- `r max_fallecidos$Region[2]`: `r commac(max_fallecidos$fallecidos[2])`
- `r max_fallecidos$Region[3]`: `r commac(max_fallecidos$fallecidos[3])`

Observamos que estas 3 regiones corresponden al `r percentc(sum_top3_fallecidos/total_chile)` de los casos totales.

En los últimos 7 días la **Región Metropolitana** registra un `r text_crecimiento_rm`  porcentual del `r percentc(crecimiento_rm$var)` de número de fallecidos.

Por otro lado las regiones con menos casos son: `r max_fallecidos$Region[14]` (`r commac(max_fallecidos$fallecidos[14])`), `r max_fallecidos$Region[15]` (`r commac(max_fallecidos$fallecidos[15])`) y `r max_fallecidos$Region[16]` (`r commac(max_fallecidos$fallecidos[16])`).